document.addEventListener("DOMContentLoaded", () => {
    const EXCEL_FILE = "cammy.xlsx";
    const loadingEl = document.getElementById("loading");
    const tabsEl = document.getElementById("tabs");
    const contentEl = document.getElementById("content");

    // Fetch and process the Excel file
    fetch(EXCEL_FILE)
        .then(res => {
            if (!res.ok) throw new Error("No se pudo cargar el archivo Excel");
            return res.arrayBuffer();
        })
        .then(data => {
            const workbook = XLSX.read(data, { type: "array" });
            loadingEl.style.display = "none";
            renderWorkbook(workbook);
        })
        .catch(err => {
            loadingEl.textContent = "Error: " + err.message;
            console.error(err);
        });

    function renderWorkbook(workbook) {
        const sheetNames = workbook.SheetNames;
        
        // Render tabs and content sections
        sheetNames.forEach((sheetName, index) => {
            // Create tab
            const tab = document.createElement("li");
            tab.textContent = sheetName;
            tab.dataset.target = "sheet-" + index;
            if (index === 0) tab.classList.add("active");
            
            tab.addEventListener("click", () => switchTab(tab, "sheet-" + index));
            tabsEl.appendChild(tab);

            // Create content section
            const section = document.createElement("div");
            section.id = "sheet-" + index;
            section.className = "sheet-content";
            if (index === 0) section.classList.add("active");

            // Convert sheet to HTML table
            const worksheet = workbook.Sheets[sheetName];
            const htmlTable = XLSX.utils.sheet_to_html(worksheet, { id: "table-" + index, editable: false });
            
            if (htmlTable) {
                // Some cleanup to make the table look nicer
                const tempDiv = document.createElement('div');
                tempDiv.innerHTML = htmlTable;
                const table = tempDiv.querySelector('table');
                if (table) {
                    table.removeAttribute('id');
                    // Remove inline styles generated by SheetJS to use our CSS
                    const allEls = table.querySelectorAll('*');
                    allEls.forEach(el => el.removeAttribute('style'));
                    section.appendChild(table);
                } else {
                    section.innerHTML = "<p>No hay datos en esta hoja.</p>";
                }
            } else {
                section.innerHTML = "<p>No hay datos en esta hoja.</p>";
            }

            contentEl.appendChild(section);
        });
    }

    function switchTab(activeTab, targetId) {
        // Remove active class from all tabs
        document.querySelectorAll(".tabs li").forEach(t => t.classList.remove("active"));
        // Hide all sheet contents
        document.querySelectorAll(".sheet-content").forEach(s => s.classList.remove("active"));
        
        // Activate current tab and content
        activeTab.classList.add("active");
        document.getElementById(targetId).classList.add("active");
    }
});